version: 1.0
api:
  version: v1
server:
  address: 0.0.0.0:8080
storage:
  tag: memory
  memorysettings:
    users:
      - id: 1
        name: testing
        email: testing@testing.com
  sqlsettings:
    host: mysql
    port: 3306
    user: user
    pass: password
    name: user