// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injector

import (
	"github.com/google/wire"
	"github.com/vicren/go-clean/adapter/controller"
	"github.com/vicren/go-clean/adapter/repository/memory"
	"github.com/vicren/go-clean/domain/entity"
)

// Injectors from injector.go:

func InitMemoryEngine(Users []entity.User) *controller.AppController {
	userRepository := memory.NewUserRepository(Users)
	userController := controller.NewUserController(userRepository)
	appController := controller.NewAppController(userController)
	return appController
}

// injector.go:

var MemoryProvider = wire.NewSet(controller.NewAppController, controller.UserProvider, memory.Provider)
